version: "3.8"
services:
  api:
    build: ./SimbirGOAPI
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: always
    depends_on:
      - db
    volumes:
      - ./key:/root/.aspnet/DataProtection-Keys
    ports:
      - 5000:5000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: SimbirGODb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./Db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  proxy:
    image: nginx
    restart: always
    depends_on:
      - db
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80