version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: SimbirGODb
    volumes:
      - ./Db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    image: nginx
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80