version: "3.8"
services:
  api:
    build:
      context: ./SimbirGOAPI
      dockerfile: .dockerfile
    restart: always
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 5000:5000

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: SimbirGODb
    volumes:
      - ./Db:/var/lib/postgresql/data
    ports:
      - 5432:5432